#!/usr/bin/env python

# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# Find the sum of all the even-valued terms in the sequence which do not exceed
# four million.

import itertools
import common

def inffibseq():
    f2 = 1
    f1 = 0
    fn = 0
    while True:
        yield fn
        fn = f1 + f2
        f1,f2 = fn,f1

def fib(n):
    return common.nth(inffibseq(), n)

print sum(itertools.takewhile(lambda x: x < 4000000,
                              itertools.ifilter(lambda x: x % 2 == 0,
                                                inffibseq())))
