#!/usr/bin/env python

# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
# Triangle   Tn=n(n+1)/2   1, 3, 6, 10, 15, ...
# Pentagonal   Pn=n(3n1)/2   1, 5, 12, 22, 35, ...
# Hexagonal   Hn=n(2n1)   1, 6, 15, 28, 45, ...
#
# It can be verified that T285 = P165 = H143 = 40755.
#
# Find the next triangle number that is also pentagonal and hexagonal.
from math import sqrt


def triangle(n):
    return (n * (n + 1)) / 2

def hexagonal(n):
    return n*(2*n - 1)

def pentagonal(n):
    return (n * (3*n-1)) / 2


def ispent(n):

    pn = (0.5 + sqrt(0.25 + 6 * n)) / 3
    nn = (0.5 - sqrt(0.25 + 6 * n)) / 3
    
    pnworks = False
    if (pn > 0):
        pnworks = pentagonal(int(pn)) == n

    nnworks = False
    if (nn > 0):
        nnworks = pentagonal(int(Pn)) == n

    return pnworks or nnworks

def ishex(n):
    pn = (1 + sqrt(1 + 8 * n)) / 4
    nn = (1 - sqrt(1 + 8 * n)) / 4

    pnworks = False
    if (pn > 0):
        pnworks = hexagonal(int(pn)) == n

    nnworks = False
    if (nn > 0):
        nnworks = hexagonal(int(Pn)) == n

    return pnworks or nnworks

for n in xrange(0, 100000):
    tnum = triangle(n)
    if ishex(tnum) and ispent(tnum):
        print tnum
